/*
 * Builds the documentation site.
 *
 *   docs/src/*.md  →  docs/index.html
 *                     docs/<slug>/index.html   (one page per section)
 *                     docs/print.html          (all sections, for the PDF)
 *                     docs/search-index.json
 *                     docs/assets/thumb-*.svg
 *
 * Multipage rather than one long scroll: each section is a URL someone can
 * link to and land on, which is what documentation is for. The single-page
 * version still exists as print.html, because a PDF wants one continuous
 * document and a reader offline wants all of it.
 *
 * docs/assets/docs.css and docs/assets/docs.js are hand-authored and are not
 * generated by this script — it only writes HTML, the search index and the
 * section artwork.
 *
 * The site is published at theme.imswarnil.com/docs/. GitHub Pages serves the
 * repository root, so this folder — docs/ — lands at /docs/ without any path
 * rewriting, and CNAME and .nojekyll are written to the repository root rather
 * than in here. Every internal link and asset href is built from BASE below.
 *
 * print.html is the exception to all of it: the PDF step opens it as a local
 * file, so its CSS is inlined and it links to nothing.
 *
 *   npm run docs
 */

import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { marked } from 'marked';

const ROOT = process.cwd();
const SRC = join(ROOT, 'docs', 'src');
const OUT = join(ROOT, 'docs');
const ASSETS = join(OUT, 'assets');

const { version, description, docsSite } = JSON.parse(
	await readFile(join(ROOT, 'package.json'), 'utf8'),
);

/* Where the documentation is published, from package.json → docsSite.
 *
 * This is configuration rather than a constant because the obvious domain is
 * already taken: theme.imswarnil.com is a live Ghost site — the theme's own
 * demo — not a static host. Pointing a GitHub Pages CNAME at it would fight
 * the site it is meant to document.
 *
 * BASE is the path the docs live under, and every internal link, asset href and
 * canonical URL is built from it. The search script reads it off <html
 * data-base>, so moving the docs is one edit in package.json. */
const SITE = docsSite.origin.replace(/\/+$/, '');
const BASE = docsSite.base;

/* Cache busting for the two hand-authored assets. Keyed to their contents, not
   to the theme version: during a docs session the version does not move, and a
   browser holding a stale stylesheet looks exactly like a CSS bug. */
const ASSET_DIR = join(ROOT, 'docs', 'assets');
const stamp = async (file) => {
	const hash = createHash('sha1')
		.update(await readFile(join(ASSET_DIR, file)))
		.digest('hex')
		.slice(0, 8);
	return `${BASE}assets/${file}?v=${hash}`;
};

const CSS_HREF = await stamp('docs.css');
const JS_HREF = await stamp('docs.js');

/* Where the live preview points. Until the demo is hosted this is unset and the
   home page falls back to the captured screenshots, which are committed. Set it
   to the demo's URL and the same block becomes a real embedded site. */
const DEMO_URL = process.env.DEMO_URL || '';

/* ── Icons ────────────────────────────────────────────────────────────────
   The same drawing conventions as the theme's own partials/icon.hbs — 24×24,
   1.75 stroke, round caps — so the two never look like different sets. */
const ICONS = {
	download: '<path d="M12 3v12M7 11l5 5 5-5M4 20h16"/>',
	play: '<path d="M8 5.5v13l11-6.5z" fill="currentColor" stroke="none"/>',
	sliders: '<path d="M4 8h10M18 8h2M4 16h4M12 16h8"/><circle cx="16" cy="8" r="2"/><circle cx="10" cy="16" r="2"/>',
	layout: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M9 9v11"/>',
	package: '<path d="M12 3l8 4.5v9L12 21l-8-4.5v-9L12 3z"/><path d="M4 7.5l8 4.5 8-4.5M12 12v9"/>',
	brush: '<path d="M4 20c2 0 3-1 3-3a2 2 0 1 0-3 3zM9 15L18.5 5.5a2.1 2.1 0 0 1 3 3L12 18"/>',
	help: '<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3 2.5v1.5M12 17h.01"/>',
	search: '<circle cx="11" cy="11" r="7"/><path d="M20 20l-3.5-3.5"/>',
	menu: '<path d="M4 7h16M4 12h16M4 17h16"/>',
	close: '<path d="M6 6l12 12M18 6L6 18"/>',
	sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
	moon: '<path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/>',
	system: '<rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 20h8M12 16v4"/>',
	'arrow-left': '<path d="M19 12H5M11 6l-6 6 6 6"/>',
	'arrow-right': '<path d="M5 12h14M13 6l6 6-6 6"/>',
	external: '<path d="M14 4h6v6M20 4l-9 9M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5"/>',
	book: '<path d="M4 5a2 2 0 0 1 2-2h13v16H6a2 2 0 0 0-2 2z"/><path d="M4 19a2 2 0 0 1 2-2h13"/>',
};

const icon = (name, cls = 'icon') =>
	`<svg class="${cls}" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${ICONS[name] || ''}</svg>`;

const escapeHtml = (text) =>
	String(text).replace(/[&<>"]/g, (c) =>
		({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);

const slugify = (text) =>
	text.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-');

/* ── Read the sources ─────────────────────────────────────────────────── */

const parse = (source, file) => {
	const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
	if (!match) throw new Error(`${file}: missing front matter`);
	const meta = {};
	for (const line of match[1].split('\n')) {
		const pair = line.match(/^(\w+):\s*(.*)$/);
		if (pair) meta[pair[1]] = /^\d+$/.test(pair[2].trim()) ? Number(pair[2]) : pair[2].trim();
	}
	return { meta, body: match[2] };
};

const files = (await readdir(SRC)).filter((f) => f.endsWith('.md')).sort();

const pages = [];
for (const file of files) {
	const { meta, body } = parse(await readFile(join(SRC, file), 'utf8'), file);
	const headings = [];

	// Render once, collecting h2/h3 for the contents rail and giving every
	// heading a stable id and a hover anchor.
	const html = marked.parse(body).replace(
		/<h([23])>([\s\S]*?)<\/h\1>/g,
		(_, level, inner) => {
			const plain = inner.replace(/<[^>]+>/g, '');
			const id = slugify(plain);
			headings.push({ id, text: plain, level: Number(level) });
			return `<h${level} id="${id}">${inner}<a class="anchor" href="#${id}" aria-label="Link to this section">#</a></h${level}>`;
		},
	);

	pages.push({ ...meta, html, headings, raw: body });
}

pages.sort((a, b) => a.order - b.order);

/* Groups, in the order they first appear — the front matter decides the
   structure, so adding a section never means editing this file. */
const groups = [];
for (const page of pages) {
	let group = groups.find((g) => g.name === page.group);
	if (!group) groups.push((group = { name: page.group, pages: [] }));
	group.pages.push(page);
}

/* ── Section artwork ──────────────────────────────────────────────────────
   One flat SVG per section, drawn from the same two-ramp palette as the theme
   and deterministic from the section's order number. Drawn rather than
   photographed: no licences, no weight, and it cannot go out of date. */
const thumb = (page) => {
	const W = 1600;
	const H = 900;
	const g = 100;
	const compositions = [
		`<circle cx="${W * 0.68}" cy="${H * 0.5}" r="${g * 2}" fill="#f04e2e"/>
		 <rect x="${g * 2}" y="${H * 0.5 - g}" width="${g * 3.5}" height="${g * 2}" fill="#191922"/>`,
		`<rect x="${W * 0.56}" y="${g}" width="${g * 4.5}" height="${H - g * 2}" fill="#191922"/>
		 <circle cx="${W * 0.56}" cy="${H * 0.5}" r="${g * 1.2}" fill="#f04e2e"/>`,
		`<path d="M ${g * 2} ${H - g * 2} L ${W * 0.5} ${g * 1.5} L ${W - g * 2} ${H - g * 2} Z" fill="#191922"/>
		 <circle cx="${W * 0.5}" cy="${H * 0.64}" r="${g * 0.9}" fill="#f04e2e"/>`,
		`<rect x="${g * 2}" y="${g * 2}" width="${W - g * 4}" height="${H - g * 4}" fill="none" stroke="#191922" stroke-width="14"/>
		 <rect x="${W * 0.5}" y="${g * 2}" width="${W * 0.5 - g * 2}" height="${H - g * 4}" fill="#f04e2e"/>`,
		`<circle cx="${W * 0.4}" cy="${H * 0.5}" r="${g * 2.1}" fill="none" stroke="#191922" stroke-width="16"/>
		 <circle cx="${W * 0.62}" cy="${H * 0.5}" r="${g * 2.1}" fill="#f04e2e" opacity="0.92"/>`,
		`<rect x="${g * 2}" y="${H * 0.5 - g * 1.3}" width="${W - g * 4}" height="${g * 2.6}" fill="#191922"/>
		 <rect x="${W - g * 5}" y="${H * 0.5 - g * 1.3}" width="${g * 2.6}" height="${g * 2.6}" fill="#d9a33a"/>`,
		`<path d="M ${g * 2} ${H * 0.5} L ${W * 0.42} ${g * 1.6} L ${W * 0.42} ${H - g * 1.6} Z" fill="#f04e2e"/>
		 <rect x="${W * 0.52}" y="${g * 1.6}" width="${g * 4}" height="${H - g * 3.2}" fill="#191922"/>`,
	];

	return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="${escapeHtml(page.title)}">
  <rect width="${W}" height="${H}" fill="#f1f1f4"/>
  <g stroke="#d3d3db" stroke-width="2">
    ${Array.from({ length: 15 }, (_, i) => `<line x1="${(i + 1) * 100}" y1="0" x2="${(i + 1) * 100}" y2="${H}"/>`).join('')}
    ${Array.from({ length: 8 }, (_, i) => `<line x1="0" y1="${(i + 1) * 100}" x2="${W}" y2="${(i + 1) * 100}"/>`).join('')}
  </g>
  ${compositions[(page.order - 1) % compositions.length]}
  <text x="90" y="${H - 90}" font-family="ui-monospace, monospace" font-size="64" fill="#76768a" letter-spacing="8">${String(page.order).padStart(2, '0')}</text>
</svg>
`;
};

/* ── Shared chrome ────────────────────────────────────────────────────── */

const sidebar = (current) => groups
	.map((group) => `
        <div class="nav__group">
          <p class="nav__label">${escapeHtml(group.name)}</p>
          <ul class="nav__list">
${group.pages.map((page) => `            <li><a class="nav__link" href="${BASE}${page.slug}/"${page.slug === current ? ' aria-current="page"' : ''}>${icon(page.icon)}${escapeHtml(page.title)}</a></li>`).join('\n')}
          </ul>
        </div>`)
	.join('\n');

const head = (title, canonical, summary) => `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<meta name="description" content="${escapeHtml(summary)}">
<link rel="canonical" href="${canonical}">
<meta property="og:title" content="${escapeHtml(title)}">
<meta property="og:description" content="${escapeHtml(summary)}">
<meta property="og:url" content="${canonical}">
<meta property="og:type" content="website">
<meta name="theme-color" content="#f04e2e">
<link rel="stylesheet" href="${CSS_HREF}">
<script>
  /* Applied before first paint — deferring it means a white flash on every
     page for anyone reading in dark mode. */
  (function () {
    var scheme = 'system';
    try { scheme = localStorage.getItem('swarnil-docs-scheme') || 'system'; } catch (e) {}
    var root = document.documentElement;
    root.dataset.scheme = scheme;
    if (scheme !== 'system') {
      root.dataset.theme = scheme;
    }
  })();
</script>`;

const header = () => `
  <header class="header">
    <div class="wrap header__inner">
      <a class="brand" href="${BASE}">
        <span class="brand__dot"></span>
        <span>Swarnil</span>
        <span class="brand__version">v${version}</span>
      </a>

      <div class="header__spacer"></div>

      <nav class="header__links" aria-label="Site">
        <a href="${BASE}">Documentation</a>
        <a href="${SITE}/#preview">Preview</a>
        <a href="https://github.com/imswarnil/Swarnil-Ghost-Theme">Repository</a>
      </nav>

      <button class="search-open" data-search-open hidden>
        ${icon('search')}
        <span class="search-open__label">Search</span>
        <kbd class="search-open__hint">/</kbd>
      </button>

      <button class="btn btn--icon" data-scheme-toggle aria-label="Change colour scheme">
        <span data-scheme-icon="system">${icon('system')}</span>
        <span data-scheme-icon="light" hidden>${icon('sun')}</span>
        <span data-scheme-icon="dark" hidden>${icon('moon')}</span>
      </button>

      <button class="btn btn--icon nav-toggle" data-drawer-open aria-expanded="false" aria-controls="drawer" aria-label="Open navigation">
        ${icon('menu')}
      </button>
    </div>
  </header>`;

const footer = () => `
  <footer class="footer">
    <div class="wrap footer__inner">
      <span>Swarnil v${version} · Ghost 6.0+</span>
      <span><a href="${BASE}assets/docs.pdf">Download as PDF</a> · <a href="${SITE}">theme.imswarnil.com</a></span>
    </div>
  </footer>`;

const drawer = (current) => `
  <dialog class="drawer" id="drawer" data-drawer aria-label="Navigation">
    <div class="drawer__inner">
      <div class="drawer__head">
        <span class="brand"><span class="brand__dot"></span><span>Swarnil</span></span>
        <button class="btn btn--icon" data-drawer-close aria-label="Close navigation">${icon('close')}</button>
      </div>
      <nav aria-label="Documentation">${sidebar(current)}
      </nav>
    </div>
  </dialog>`;

const searchDialog = () => `
  <dialog class="search" data-search aria-label="Search the documentation">
    <div class="search__field">
      ${icon('search')}
      <input class="search__input" data-search-input type="search" placeholder="Search the documentation" aria-label="Search the documentation" autocomplete="off" spellcheck="false">
      <button class="btn btn--icon" data-search-close aria-label="Close search">${icon('close')}</button>
    </div>
    <ul class="search__results" data-search-results></ul>
  </dialog>`;

const shell = ({ title, canonical, summary, body, current }) => `<!DOCTYPE html>
<html lang="en" data-base="${BASE}">
<head>
${head(title, canonical, summary)}
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<div class="shell">
${header()}
${body}
${footer()}
</div>
${drawer(current)}
${searchDialog()}
<script src="${JS_HREF}"></script>
</body>
</html>
`;

/* ── Section pages ────────────────────────────────────────────────────── */

const tocFor = (page) => {
	if (page.headings.length < 2) return '';
	return `
        <aside class="rail" aria-label="On this page">
          <p class="nav__label">On this page</p>
          <ul class="toc__list">
${page.headings.map((h) => `            <li class="toc__item${h.level === 3 ? ' toc__item--sub' : ''}"><a class="toc__link" data-toc-link href="#${h.id}">${escapeHtml(h.text)}</a></li>`).join('\n')}
          </ul>
        </aside>`;
};

const pagerFor = (index) => {
	const prev = pages[index - 1];
	const next = pages[index + 1];
	if (!prev && !next) return '';
	return `
          <nav class="pager" aria-label="Section">
${prev ? `            <a class="pager__link pager__link--prev" href="${BASE}${prev.slug}/" rel="prev">
              <span class="pager__dir">${icon('arrow-left')} Previous</span>
              <span class="pager__title">${escapeHtml(prev.title)}</span>
            </a>` : ''}
${next ? `            <a class="pager__link pager__link--next" href="${BASE}${next.slug}/" rel="next">
              <span class="pager__dir">Next ${icon('arrow-right')}</span>
              <span class="pager__title">${escapeHtml(next.title)}</span>
            </a>` : ''}
          </nav>`;
};

await mkdir(ASSETS, { recursive: true });

for (const [index, page] of pages.entries()) {
	const body = `
  <div class="wrap page">
    <nav class="sidebar" aria-label="Documentation">${sidebar(page.slug)}
    </nav>

    <main class="content" id="main">
      <div class="page-head">
        <p class="page-head__kicker slate">${escapeHtml(page.group)} · ${String(page.order).padStart(2, '0')}</p>
        <h1>${escapeHtml(page.title)}</h1>
        <p class="page-head__summary">${escapeHtml(page.summary)}</p>
      </div>

      <div class="prose">
${page.html}
      </div>
${pagerFor(index)}
    </main>
${tocFor(page)}
  </div>`;

	await mkdir(join(OUT, page.slug), { recursive: true });
	await writeFile(
		join(OUT, page.slug, 'index.html'),
		shell({
			title: `${page.title} — Swarnil documentation`,
			canonical: `${SITE}${BASE}${page.slug}/`,
			summary: page.summary,
			body,
			current: page.slug,
		}),
	);
	await writeFile(join(ASSETS, `thumb-${page.slug}.svg`), thumb(page));
}

/* ── Home ─────────────────────────────────────────────────────────────── */

const previewBlock = () => {
	const stage = DEMO_URL
		? `<iframe src="${DEMO_URL}" title="Live preview of the Swarnil theme" loading="lazy" referrerpolicy="no-referrer"></iframe>`
		: `<img class="preview__shot" src="${BASE}assets/preview-home.png" alt="The Swarnil theme's homepage: a large site title, a featured post with a framed image, and a numbered index of posts below." width="1600" height="1000" loading="lazy">`;

	return `
  <section class="wrap preview" id="preview">
    <div class="preview__head">
      <div>
        <p class="slate" style="margin:0 0 .4rem">Live preview</p>
        <h2 style="margin:0;font-size:1.5rem;letter-spacing:-.015em">See it at three widths</h2>
      </div>
      <div class="preview__widths" role="group" aria-label="Preview width">
        <button class="preview__width" data-preview-width="full" aria-pressed="true">Desktop</button>
        <button class="preview__width" data-preview-width="tablet" aria-pressed="false">Tablet</button>
        <button class="preview__width" data-preview-width="phone" aria-pressed="false">Phone</button>
      </div>
    </div>

    <div class="preview__frame">
      <div class="preview__viewport" data-preview-viewport data-width="full">
        <div class="preview__chrome">
          <span class="preview__dot"></span><span class="preview__dot"></span><span class="preview__dot"></span>
          <span class="preview__url">${DEMO_URL || 'theme.imswarnil.com'}</span>
        </div>
        <div class="preview__stage">${stage}</div>
      </div>
    </div>

    <p class="preview__note">${DEMO_URL
		? 'The frame changes width, not the zoom — what you are seeing is the theme’s own responsive behaviour.'
		: 'A capture of the theme running in Ghost. The live demo is not published yet; the width control still shows how the layout reflows.'}</p>
  </section>`;
};

const homeBody = `
  <section class="wrap hero">
    <p class="hero__kicker slate">Ghost theme · v${version}</p>
    <h1>Documentation for the Swarnil theme</h1>
    <p class="hero__lede">${escapeHtml(description)}</p>
    <div class="hero__actions">
      <a class="btn btn--primary" href="${BASE}install/">${icon('download')} Install the theme</a>
      <a class="btn btn--outline" href="${BASE}settings/">${icon('sliders')} Settings reference</a>
      <a class="btn btn--outline" href="${BASE}assets/docs.pdf">${icon('book')} Read as PDF</a>
    </div>
  </section>

${previewBlock()}

  <main class="wrap sections" id="main">
${groups.map((group) => `    <div class="sections__group">
      <div class="sections__head">
        <h2 class="sections__title">${escapeHtml(group.name)}</h2>
        <span class="slate">${group.pages.length} ${group.pages.length === 1 ? 'page' : 'pages'}</span>
      </div>
      <ul class="cards">
${group.pages.map((page) => `        <li class="card">
          <img class="card__thumb" src="${BASE}assets/thumb-${page.slug}.svg" alt="" width="1600" height="900" loading="lazy">
          <div class="card__body">
            <p class="card__index">${icon('' + page.icon)} ${String(page.order).padStart(2, '0')}</p>
            <h3 class="card__title"><a href="${BASE}${page.slug}/">${escapeHtml(page.title)}</a></h3>
            <p class="card__summary">${escapeHtml(page.summary)}</p>
          </div>
        </li>`).join('\n')}
      </ul>
    </div>`).join('\n')}
  </main>`;

await writeFile(
	join(OUT, 'index.html'),
	shell({
		title: 'Swarnil — Ghost theme documentation',
		canonical: `${SITE}${BASE}`,
		summary: description,
		body: homeBody,
		current: '',
	}),
);

/* ── Print page ───────────────────────────────────────────────────────────
   Every section in order, one document, with the stylesheet inlined because
   the PDF step opens this as a local file. */
const css = await readFile(join(ASSETS, 'docs.css'), 'utf8');

const printPage = `<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<title>Swarnil — Ghost theme documentation v${version}</title>
<style>
${css}
</style>
</head>
<body>
<div class="wrap" style="padding-top:2rem">
  <p class="slate" style="color:var(--accent-text)">Ghost theme documentation</p>
  <h1 style="font-size:2.5rem;margin:.5rem 0 0;letter-spacing:-.03em">Swarnil</h1>
  <p style="max-width:34rem;color:var(--fg-muted)">${escapeHtml(description)}</p>
  <p class="slate">Version ${version} · Ghost 6.0+ · ${SITE}</p>
</div>

<div class="wrap">
${pages.map((page) => `<section class="print-section">
  <div class="page-head">
    <p class="page-head__kicker slate">${escapeHtml(page.group)} · ${String(page.order).padStart(2, '0')}</p>
    <h1>${escapeHtml(page.title)}</h1>
    <p class="page-head__summary">${escapeHtml(page.summary)}</p>
  </div>
  <div class="prose">
${page.html}
  </div>
</section>`).join('\n')}
</div>
</body>
</html>
`;

await writeFile(join(OUT, 'print.html'), printPage);

/* ── Search index ─────────────────────────────────────────────────────────
   One entry per heading, so a result lands on the right part of a page rather
   than at its top. Built from the raw Markdown — stripping the markup before
   splitting would remove the '#' the split depends on, which quietly collapsed
   every page down to a single entry the first time. */
const stripMarkdown = (text) => text
	.replace(/```[\s\S]*?```/g, ' ')          // fenced code
	.replace(/`([^`]*)`/g, '$1')              // inline code
	.replace(/!?\[([^\]]*)\]\([^)]*\)/g, '$1') // links and images
	.replace(/[*_>|]/g, ' ')
	.replace(/\s+/g, ' ')
	.trim();

const entries = [];
for (const page of pages) {
	entries.push({
		page: page.title,
		heading: '',
		url: `${page.slug}/`,
		text: page.summary,
	});

	for (const chunk of page.raw.split(/\n(?=#{2,3}\s)/)) {
		const title = chunk.match(/^(#{2,3})\s+(.+)$/m);
		const text = stripMarkdown(chunk.replace(/^#{2,3}\s+.+$/m, '')).slice(0, 600);
		if (!text) continue;
		entries.push({
			page: page.title,
			heading: title ? title[2].trim() : '',
			url: title ? `${page.slug}/#${slugify(title[2].trim())}` : `${page.slug}/`,
			text,
		});
	}
}

await writeFile(join(OUT, 'search-index.json'), JSON.stringify(entries));

/* GitHub Pages serves the repository root, so these belong there rather than in
   docs/. Without .nojekyll, Pages tries to build the whole repository —
   including the theme's .hbs files — as a Jekyll site.

   A CNAME is written only when docsSite.domain is set. It is empty by default
   on purpose: writing one for a domain that already serves something else does
   not fail loudly, it just quietly competes with the real site. */
await writeFile(join(ROOT, '.nojekyll'), '');

if (docsSite.domain) {
	await writeFile(join(ROOT, 'CNAME'), `${docsSite.domain}\n`);
} else {
	await rm(join(ROOT, 'CNAME'), { force: true });
}

console.log(
	`docs — ${pages.length} pages in ${groups.length} groups, ` +
	`${entries.length} search entries, ${pages.length} thumbnails` +
	(DEMO_URL ? `, live preview → ${DEMO_URL}` : ', preview from screenshot'),
);
